apiVersion: v1
kind: Service
metadata:
  name: student-service
  labels:
    name: student-profile-app
    app: student-profile-app
spec:
  type: NodePort
  selector:
    name: student-profile-app
    app: student-profile-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30005
